Repository BDSA-2021/BDSA21-Say-AAAAAA, pull requests merged in 2021-11, with the labels that each got.

#4 Add solution file
  BDSA2021.sln
Labels: enhancement

#5 Add frontend
  BDSA2021.sln
  SELearning.Tests/SELearning.Tests.csproj
  SELearning.Tests/UnitTest1.cs
  SELearning/App.razor
  SELearning/Data/WeatherForecast.cs
  SELearning/Data/WeatherForecastService.cs
  SELearning/Pages/Counter.razor
  SELearning/Pages/Error.cshtml
  SELearning/Pages/Error.cshtml.cs
  SELearning/Pages/FetchData.razor
  SELearning/Pages/Index.razor
  SELearning/Pages/_Host.cshtml
  SELearning/Pages/_Layout.cshtml
  SELearning/Program.cs
  SELearning/Properties/launchSettings.json
  SELearning/SELearning.csproj
  SELearning/Shared/MainLayout.razor
  SELearning/Shared/MainLayout.razor.css
  SELearning/Shared/NavMenu.razor
  SELearning/Shared/NavMenu.razor.css
  SELearning/Shared/SurveyPrompt.razor
  SELearning/_Imports.razor
  SELearning/appsettings.Development.json
  SELearning/appsettings.json
  SELearning/wwwroot/css/bootstrap/bootstrap.min.css
  SELearning/wwwroot/css/bootstrap/bootstrap.min.css.map
  SELearning/wwwroot/css/open-iconic/FONT-LICENSE
  SELearning/wwwroot/css/open-iconic/ICON-LICENSE
  SELearning/wwwroot/css/open-iconic/README.md
  SELearning/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  SELearning/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  SELearning/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  SELearning/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  SELearning/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  SELearning/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  SELearning/wwwroot/css/site.css
  SELearning/wwwroot/favicon.ico
Labels: enhancement, good first issue

#6 [FEATURE] Workflows
  .github/workflows/build-and-test.yml
  .github/workflows/check-formatting.yml
Labels: enhancement, meta

#8 [FEATURE] Scaffolded Core, API, Infrastructure
  BDSA2021.sln
  SELearning.Api.Tests/SELearning.Api.Tests.csproj
  SELearning.Api/Controllers/WeatherForecastController.cs
  SELearning.Api/Program.cs
  SELearning.Api/Properties/launchSettings.json
  SELearning.Api/SELearning.Api.csproj
  SELearning.Api/WeatherForecast.cs
  SELearning.Api/appsettings.Development.json
  SELearning.Api/appsettings.json
  SELearning.Core/README.md
  SELearning.Core/SELearning.Core.csproj
  SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
  SELearning.Infrastructure/README.md
  SELearning.Infrastructure/SELearning.Infrastructure.csproj
Labels: enhancement

#7 [FIX] Move pull request template to .github
  .github/pull_request_template.md
Labels: bug, meta

#9 [FEATURE] Azure authentication and front end scaffolding
  BDSA2021.sln
  README.md
  SELearning.Api.Tests/SELearning.Api.Tests.csproj
  SELearning.Api/Controllers/WeatherForecastController.cs
  SELearning.Api/Program.cs
  SELearning.Api/Properties/launchSettings.json
  SELearning.Api/SELearning.Api.csproj
  SELearning.Api/appsettings.Development.json
  SELearning.Api/appsettings.json
  SELearning.Core/GlobalUsings.cs
  SELearning.Core/WeatherForecastDTO.cs
  SELearning.Core/WeatherForecastRepository.cs
  SELearning.Infrastructure/GlobalUsings.cs
  SELearning.Infrastructure/IWeatherContext.cs
  SELearning.Infrastructure/Migrations/20211123231722_InitialMigration.Designer.cs
  SELearning.Infrastructure/Migrations/20211123231722_InitialMigration.cs
  SELearning.Infrastructure/Migrations/WeatherContextModelSnapshot.cs
  SELearning.Infrastructure/SELearning.Infrastructure.csproj
  SELearning.Infrastructure/WeatherContext.cs
  SELearning.Infrastructure/WeatherForecast.cs
  SELearning.Infrastructure/WeatherForecastRepository.cs
  SELearning/App.razor
  SELearning/Data/WeatherForecast.cs
  SELearning/Data/WeatherForecastService.cs
  SELearning/GlobalUsings.cs
  SELearning/Pages/Counter.razor
  SELearning/Pages/Error.cshtml
  SELearning/Pages/Error.cshtml.cs
  SELearning/Pages/FetchData.razor
  SELearning/Pages/Index.razor
  SELearning/Pages/_Host.cshtml
  SELearning/Pages/_Layout.cshtml
  SELearning/Program.cs
  SELearning/Properties/launchSettings.json
  SELearning/SELearning.csproj
  SELearning/Services/WeatherForecastService.cs
  SELearning/Shared/LoginDisplay.razor
  SELearning/Shared/MainLayout.razor
  SELearning/Shared/MainLayout.razor.css
  SELearning/Shared/NavMenu.razor
  SELearning/Shared/NavMenu.razor.css
  SELearning/Shared/SurveyPrompt.razor
  SELearning/_Imports.razor
  SELearning/appsettings.Development.json
  SELearning/appsettings.json
  SELearning/wwwroot/css/bootstrap/bootstrap.min.css
  SELearning/wwwroot/css/bootstrap/bootstrap.min.css.map
  SELearning/wwwroot/css/site.css
Labels: enhancement

#16 [FEATURE] Implement permission service
  .gitignore
  SELearning.Core/Permission/IPermissionService.cs
  SELearning.Core/Permission/Permission.cs
  SELearning.Core/Permission/PermissionDecider.cs
  SELearning.Core/Permission/Rule.cs
  SELearning.Infrastructure.Tests/Permission/PermissionDeciderTests.cs
Labels: enhancement

#13 [FEATURE] Comment
  SELearning.Core/Comment.cs
  SELearning.Core/Services/ICommentService.cs
  SELearning.Infrastructure.Tests/CommentManagerTests.cs
  SELearning.Infrastructure/CommentManager.cs
Labels: enhancement

#18 [FEATURE] Content structure created
  .DS_Store
  SELearning.Core/.DS_Store
  SELearning.Core/Content/Content.cs
  SELearning.Core/Content/ContentManager.cs
  SELearning.Core/Content/IContentRepository.cs
  SELearning.Core/Content/IContentService.cs
  SELearning.Core/Content/Section.cs
  SELearning.Infrastructure.Tests/Content/ContentRepositoryTests.cs
  SELearning.Infrastructure.Tests/Content/GlobalUsings.cs
  SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
  SELearning.Infrastructure/ContentContext.cs
  SELearning.Infrastructure/ContentRepository.cs
  SELearning.Infrastructure/GlobalUsings.cs
  SELearning.Infrastructure/IContentContext.cs
Labels: enhancement

#10 [FEATURE] Add credibility service
  SELearning.Core/CredibilityRepository.cs
  SELearning.Core/User.cs
  SELearning.Core/services/CredibilityService.cs
  SELearning.Infrastructure.Tests/GlobalUsings.cs
  SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
  SELearning.Infrastructure.Tests/services/CredibilityCalculatorTests.cs
  SELearning.Infrastructure/services/CredibilityCalculator.cs
Labels: enhancement, wip
