Repository BDSA-2021/BDSA21-Say-AAAAAA, pull requests merged in 2021-12, with the labels that each got.

#17 [FEATURE|META] Azure deployment
  .dockerignore
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-and-test.yml
  .github/workflows/check-formatting.yml
  .gitignore
  Azure.md
  BDSA2021.sln
  Dockerfile
  README.md
  SELearning.API/Controllers/WeatherForecastController.cs
  SELearning.API/Models/Migrator.cs
  SELearning.API/Program.cs
  SELearning.Core/WeatherForecastDTO.cs
  SELearning.Core/WeatherForecastRepository.cs
  SELearning.Infrastructure/WeatherForecastRepository.cs
  SELearning/Pages/FetchData.razor
  SELearning/SELearning.csproj
  docker-compose.yml
  scripts/Dockerfile.db
  scripts/create-db.sql
  scripts/docker-compose-init.sh
  scripts/entrypoint.db.sh
  scripts/entrypoint.sh
Labels: enhancement, meta

#20 [FEATURE] Authorization attributes
  BDSA2021.sln
  SELearning.Core/Permission/IPermissionService.cs
  SELearning.Core/Permission/PermissionDecider.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionAttributeTests.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionAuthorizationHandlerTests.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionPolicyProviderTests.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionRequirementTests.cs
  SELearning.Infrastructure.Tests/GlobalUsings.cs
  SELearning.Infrastructure.Tests/Permission/PermissionDeciderTests.cs
  SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
  SELearning.Infrastructure/Authorization/AuthorizationConstants.cs
  SELearning.Infrastructure/Authorization/PermissionAttribute.cs
  SELearning.Infrastructure/Authorization/PermissionAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs
  SELearning.Infrastructure/Authorization/PermissionRequirement.cs
  SELearning.Infrastructure/SELearning.Infrastructure.csproj
Labels: enhancement

#25 [FEATURE] Tested and implemented ASP.NET Web API Controllers
  BDSA2021.sln
  SELearning.API.Tests/CommentControllerTest.cs
  SELearning.API.Tests/ContentControllerTest.cs
  SELearning.API.Tests/SELearning.API.Tests.csproj
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/Controllers/ContentController.cs
  SELearning.API/Controllers/Extensions.cs
  SELearning.Core/CommentDTO.cs
  SELearning.Core/Content/IContentRepository.cs
  SELearning.Core/ContentDTO.cs
  SELearning.Core/ICommentRepository.cs
  SELearning.Core/OperationResult.cs
  SELearning.Core/Option.cs
  SELearning.Infrastructure/ContentRepository.cs
Labels: enhancement

#24 [META] Add VS Code devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/mssql/installSQLtools.sh
  .devcontainer/mssql/postCreateCommand.sh
Labels: enhancement, meta

#27 [FEATURE] Content page
  SELearning/Pages/Content.razor
  SELearning/Pages/Content.razor.css
  SELearning/Shared/Comment/CommentSection.razor
  SELearning/Shared/NavMenu.razor
Labels: enhancement, wip

#31 [FEATURE]Add Permission Authorization
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/Controllers/ContentController.cs
  SELearning.API/GlobalUsings.cs
  SELearning.API/Program.cs
  SELearning.Core/CredibilityRepository.cs
  SELearning.Core/Permission/IPermissionCredibilityService.cs
  SELearning.Core/Permission/PermissionCredibilityService.cs
  SELearning.Core/Permission/PermissionDecider.cs
  SELearning.Core/Permission/Rule.cs
  SELearning.Core/Services/ICredibilityService.cs
  SELearning.Core/services/CredibilityService.cs
  SELearning.Infrastructure.Tests/Authorization/AuthorizePermissionAttributeTests.cs
  SELearning.Infrastructure.Tests/Authorization/CredibilityAuthorizationHandlerTests.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionAuthorizationHandlerTests.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionPolicyProviderTests.cs
  SELearning.Infrastructure.Tests/Permission/PermissionDeciderTests.cs
  SELearning.Infrastructure.Tests/services/CredibilityCalculatorTests.cs
  SELearning.Infrastructure/Authorization/AuthorizationConfiguration.cs
  SELearning.Infrastructure/Authorization/AuthorizationConstants.cs
  SELearning.Infrastructure/Authorization/AuthorizationExtensions.cs
  SELearning.Infrastructure/Authorization/AuthorizePermissionAttribute.cs
  SELearning.Infrastructure/Authorization/CredibilityAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/CredibilityPermissionRequirement.cs
  SELearning.Infrastructure/Authorization/PermissionAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/PermissionBuilder.cs
  SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs
  SELearning.Infrastructure/services/CredibilityCalculator.cs
Labels: enhancement

#30 [DOCS] Create documentation for the Web API Controllers
  SELearning.API.Tests/CommentControllerTest.cs
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/Controllers/ContentController.cs
Labels: documentation

#35 [FEATURE] Authorization 'or' evaluation of credibility permissions
  README.md
  SELearning.Infrastructure.Tests/Authorization/AuthorizePermissionAttributeTests.cs
  SELearning.Infrastructure.Tests/Authorization/CredibilityAuthorizationHandlerTests.cs
  SELearning.Infrastructure.Tests/Authorization/PermissionPolicyProviderTests.cs
  SELearning.Infrastructure/Authorization/AuthorizationConstants.cs
  SELearning.Infrastructure/Authorization/AuthorizePermissionAttribute.cs
  SELearning.Infrastructure/Authorization/CredibilityAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/CredibilityPermissionRequirement.cs
  SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs
Labels: enhancement

#38 [FIX] Make master runnable
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/Controllers/ContentController.cs
  SELearning.API/Program.cs
Labels: bug

#28 [FEATURE] Comment context
  SELearning.API.Tests/CommentControllerTest.cs
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/GlobalUsings.cs
  SELearning.API/Models/Migrator.cs
  SELearning.API/Program.cs
  SELearning.Core/Comment.cs
  SELearning.Core/Comment/Comment.cs
  SELearning.Core/Comment/CommentDTO.cs
  SELearning.Core/Comment/ICommentService.cs
  SELearning.Core/CommentDTO.cs
  SELearning.Core/CommentNotFoundException.cs
  SELearning.Core/Content/Content.cs
  SELearning.Core/ContentNotFoundException.cs
  SELearning.Core/ICommentRepository.cs
  SELearning.Core/NotFoundException.cs
  SELearning.Core/OperationResult.cs
  SELearning.Core/Services/ICommentService.cs
  SELearning.Infrastructure.Tests/CommentManagerTests.cs
  SELearning.Infrastructure.Tests/CommentRepositoryTests.cs
  SELearning.Infrastructure.Tests/GlobalUsing.cs
  SELearning.Infrastructure.Tests/SELearning.Infrastructure.Tests.csproj
  SELearning.Infrastructure/CommentContext.cs
  SELearning.Infrastructure/CommentManager.cs
  SELearning.Infrastructure/CommentRepository.cs
  SELearning.Infrastructure/ContentContext.cs
  SELearning.Infrastructure/ICommentContext.cs
  SELearning.Infrastructure/ICommentRepository.cs
  SELearning.Infrastructure/Migrations/Comment/20211208101634_AddCommentContext.Designer.cs
  SELearning.Infrastructure/Migrations/Comment/20211208101634_AddCommentContext.cs
  SELearning.Infrastructure/Migrations/Comment/CommentContextModelSnapshot.cs
  SELearning/Shared/Comment/CommentSection.razor
  SELearning/Shared/Comment/CommentTile.razor
Labels: enhancement

#37 [META] More azure
  .github/dependabot.yml
  .github/workflows/infrastructure.yml
  .infrastructure/Ensure-DatabaseCreated.ps1
  .infrastructure/Grant-SqlPermission.ps1
  .infrastructure/app.bicep
  .infrastructure/azure.parameters.json
  .infrastructure/cr.bicep
  .infrastructure/main.bicep
  .infrastructure/sql.bicep
  Dockerfile
  README.md
  SELearning.API/Program.cs
  SELearning.API/SELearning.API.csproj
  SELearning.Infrastructure/SELearning.Infrastructure.csproj
  SELearning/Program.cs
  SELearning/_Imports.razor
Labels: enhancement, meta

#39 Resource based authorization
  SELearning.Core/Permission/IAuthored.cs
  SELearning.Core/Permission/Permission.cs
  SELearning.Infrastructure.Tests/Authorization/AuthoredCredibilityAuthorizationHandlerTests.cs
  SELearning.Infrastructure.Tests/Authorization/CredibilityAuthorizationHandlerTests.cs
  SELearning.Infrastructure/Authorization/AuthoredCredibilityAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/AuthorizationConfiguration.cs
  SELearning.Infrastructure/Authorization/CredibilityAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/CredibilityPermissionRequirement.cs
  SELearning.Infrastructure/Authorization/PermissionPolicyProvider.cs
Labels: enhancement

#44 [FEATURE] Implement credibility service
  SELearning.API.Tests/CommentControllerTest.cs
  SELearning.Core/Comment/CommentDTO.cs
  SELearning.Core/Comment/ICommentService.cs
  SELearning.Core/Content/ContentManager.cs
  SELearning.Core/Content/IContentRepository.cs
  SELearning.Core/Content/IContentService.cs
  SELearning.Core/ICredibilityRepository.cs
  SELearning.Infrastructure.Tests/CommentManagerTests.cs
  SELearning.Infrastructure.Tests/CommentRepositoryTests.cs
  SELearning.Infrastructure.Tests/Content/ContentRepositoryTests.cs
  SELearning.Infrastructure.Tests/Credibility/CredibilityRepositoryTest.cs
  SELearning.Infrastructure/CommentManager.cs
  SELearning.Infrastructure/CommentRepository.cs
  SELearning.Infrastructure/ContentRepository.cs
  SELearning.Infrastructure/Credibility/CredibilityRepository.cs
  SELearning.Infrastructure/ICommentRepository.cs
Labels: enhancement

#43 [FEATURE] Create new content page on the frontend
  SELearning/Pages/CreateContent.razor
  SELearning/Shared/NavMenu.razor
Labels: enhancement

#45 [FEATURE] Toast notifications
  SELearning/GlobalUsings.cs
  SELearning/Program.cs
  SELearning/Shared/MainLayout.razor
  SELearning/Shared/Toast/ToastNotification.cs
  SELearning/Shared/Toast/ToastNotificationComponent.razor
  SELearning/Shared/Toast/ToastService.cs
  SELearning/Shared/Toast/ToastType.cs
  SELearning/Shared/Toast/ToastWrapper.razor
  SELearning/_Imports.razor
  SELearning/wwwroot/index.html
  SELearning/wwwroot/js/bootstrap/bootstrap.min.js
  SELearning/wwwroot/js/bootstrap/bootstrap.min.js.map
  SELearning/wwwroot/js/module.js
Labels: enhancement

#49 [FEATURE] UI refinement and deletion of template
  SELearning.API/Controllers/WeatherForecastController.cs
  SELearning.API/Models/Migrator.cs
  SELearning.API/Program.cs
  SELearning.Core/WeatherForecastDTO.cs
  SELearning.Core/WeatherForecastRepository.cs
  SELearning.Infrastructure/IWeatherContext.cs
  SELearning.Infrastructure/Migrations/Weather/20211208124447_AddWeatherContext.Designer.cs
  SELearning.Infrastructure/Migrations/Weather/20211208124447_AddWeatherContext.cs
  SELearning.Infrastructure/Migrations/Weather/WeatherContextModelSnapshot.cs
  SELearning.Infrastructure/WeatherContext.cs
  SELearning.Infrastructure/WeatherForecast.cs
  SELearning.Infrastructure/WeatherForecastRepository.cs
  SELearning/Pages/Counter.razor
  SELearning/Pages/FetchData.razor
  SELearning/Pages/Index.razor
  SELearning/Shared/Comment/CommentSection.razor
  SELearning/Shared/NavMenu.razor
  SELearning/Shared/SurveyPrompt.razor
Labels: enhancement

#47 [FEATURE] Add authorization to the controllers
  SELearning.API.Tests/CommentControllerTest.cs
  SELearning.API.Tests/ContentControllerTest.cs
  SELearning.API.Tests/SectionControllerTest.cs
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/Controllers/ContentController.cs
  SELearning.API/Controllers/SectionController.cs
  SELearning.API/Program.cs
  SELearning.Core/Comment/CommentDTO.cs
  SELearning.Core/Content/ContentDto.cs
  SELearning.Core/Permission/Permission.cs
  SELearning.Core/Permission/PermissionCredibilityService.cs
  SELearning.Infrastructure.Tests/Authorization/AuthoredCredibilityAuthorizationHandlerTests.cs
  SELearning.Infrastructure.Tests/Authorization/CredibilityAuthorizationHandlerTests.cs
  SELearning.Infrastructure/Authorization/AuthoredCredibilityAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/AuthorizationConfiguration.cs
  SELearning.Infrastructure/Authorization/CredibilityAuthorizationHandler.cs
  SELearning.Infrastructure/Authorization/IProvider.cs
  SELearning.Infrastructure/Authorization/PermissionBuilder.cs
  SELearning.Infrastructure/Authorization/Provider.cs
Labels: enhancement

#54 [FEATURE] Show toast notifications when HTTP requests fail
  SELearning/Pages/CreateContent.razor
  SELearning/Shared/Toast/ToastNotification.cs
  SELearning/Shared/Toast/ToastWrapper.razor
Labels: enhancement

#50 All Content, Sections and Section page
  SELearning.API.Tests/ContentControllerTest.cs
  SELearning.API/Controllers/CommentController.cs
  SELearning.API/Controllers/ContentController.cs
  SELearning.API/Program.cs
  SELearning.Core/Content/ContentDto.cs
  SELearning.Core/Content/Section.cs
  SELearning.Infrastructure.Tests/Content/ContentManagerTests.cs
  SELearning.Infrastructure.Tests/Content/ContentRepositoryTests.cs
  SELearning.Infrastructure/Authorization/Provider.cs
  SELearning.Infrastructure/ContentRepository.cs
  SELearning.Infrastructure/services/CredibilityCalculator.cs
  SELearning/Pages/AllContent.razor
  SELearning/Pages/CreateSection.razor
  SELearning/Pages/Section.razor
  SELearning/Pages/Sections.razor
  SELearning/Shared/Content/AllContent.razor
  SELearning/Shared/Content/ContentInSection.razor
  SELearning/Shared/Content/ContentTile.razor
  SELearning/Shared/Content/ContentTile.razor.css
  SELearning/Shared/NavMenu.razor
  SELearning/Shared/Section/SectionTile.razor
  SELearning/Shared/Section/SectionTile.razor.css
  SELearning/Shared/Section/Sections.razor
Labels: bug, enhancement, help wanted, wip

#58 [FIX] Fixed the all content page
  SELearning/Pages/AllContent.razor
Labels: bug

#59 Change cred scores
  SELearning.Core/Permission/PermissionCredibilityService.cs
Labels: enhancement

#60 [FIX] Fixed recursion error
  SELearning.Core/Content/Section.cs
  SELearning.Infrastructure/ContentRepository.cs
Labels: bug

#65 Rollback dbcontext lifecycle
  SELearning.API/Program.cs
Labels: enhancement

#89 [TEST] Test new authorization changes in controllers
  SELearning.API.Tests/CommentControllerTest.cs
  SELearning.API.Tests/ContentControllerTest.cs
  SELearning.API.Tests/GlobalUsings.cs
  SELearning.API.Tests/SectionControllerTest.cs
  SELearning.API/Controllers/ContentController.cs
  SELearning.API/Controllers/SectionController.cs
Labels: documentation, enhancement

#87 [REFACTOR] Content refactored
  SELearning.API/SELearning.API.csproj
  SELearning/Pages/AllContent.razor
  SELearning/Pages/Section.razor
  SELearning/Shared/Content/AllContent.razor
  SELearning/Shared/Content/ContentInSection.razor
  SELearning/Shared/Content/ContentList.razor
Labels: enhancement

#91 [FEATURE] User tests
  SELearning.API.Tests/UserControllerTests.cs
  SELearning.API/Controllers/UserController.cs
  SELearning.Core/User/UserDTO.cs
  SELearning.Infrastructure.Tests/User/UserRepositoryTests.cs
  SELearning.Infrastructure.Tests/User/UserTests.cs
  SELearning/Shared/LoginDisplay.razor
Labels: enhancement

#97 [FEATURE] Dev compose
  .gitattributes
  .github/workflows/build-and-deploy.yml
  README.md
  docker-compose.dev.yml
  docker-compose.prod.yml
  docs/manual-setup.md
  scripts/Dockerfile.db
  scripts/Dockerfile.dev
  scripts/Dockerfile.prod
  scripts/docker-compose-init.ps1
  scripts/docker-compose-init.sh
  scripts/entrypoint.dev.sh
  scripts/entrypoint.prod.sh
  scripts/shared.sh
Labels: meta
